name: dart_c_l_i
description: A production-ready command-line task management application built in pure Dart.
version: 1.0.0

# Spécification de la version du SDK Dart
environment:
  sdk: ^3.12.2

# Dépendances nécessaires pour la version Pro de votre application
dependencies:
  ansicolor: ^2.0.3
  uuid: ^4.3.3

# Outils de développement et de test requis pour la validation automatique
dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.6
