name: dart_c_l_i
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'

      # 🚀 OBLIGATOIRE EN PREMIER : Crée le fichier de config dont le formateur a besoin
      - name: Install dependencies
        run: dart pub get

      # 🛠️ EN DEUXIÈME : Le formateur fonctionnera désormais sans sauter de fichier
      - name: Verify code formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Verify code formatting formatting check
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze

      - name: Run unit tests
        run: dart test
